### PR TITLE
make a responsive navbar

### PR DESCRIPTION
**Pull request by mugisha23**
issue #30

### CODE REVIEW

**Comment by mugisha23** [comment]
@lionel-k  What do you think of the navbar look on small screen ?

**Comment by lionel-k** [comment]
I think it looks great.
There is always room for improvement but on how it works we can merge it
like this.

I'll review more the code lately. But as first glance, looks good for me

**Comment by mugisha23** [comment]
Yes we may add some transition effect! I'm still trying to figure it out

**Comment by mugisha23** [comment]
What do you think of this background
Capturekkk

**Comment by lionel-k** [comment]
> What do you think of this background
> Capturekkk

Hm, I would prefer to keep the same design we have on desktop (on hover). We do not have this blue background color on desktop

**Review by lionel-k — APPROVED** [review]

**Comment by lionel-k** [comment]
@mugisha23  it looks good to me. We can merge those changes like this. What do you think ?

I added some refactor to use one state to the toggle.

**Comment by mugisha23** [comment]
> @mugisha23 it looks good to me. We can merge those changes like this. What do you think ?
> 
> I added some refactor to use one state to the toggle.

I think it's fine

**Pull request merged**
