### PR TITLE
Feature/remove unused files

### PR DESCRIPTION
**Pull request by muco-rolle**
@mugisha23 Please review this, I removed the existing styles.

### CODE REVIEW

**Comment by mugisha23** [comment]
That really looks great

**Review by mugisha23 — APPROVED** [review]

**Comment by mugisha23** [comment]
@muco-rolle can you resolve conflicts

**Comment by muco-rolle** [comment]
Merge conflict fixed.

**Comment by lionel-k** [comment]
@muco-rolle , not sure what happened here. Can you also please fix the conflict files ? Thanks

**Comment by muco-rolle** [comment]
It should be okay now.

**Comment by lionel-k** [comment]
Not really 😌. You should try to merge the master branch and fix the conflicts.

**Comment by muco-rolle** [comment]
@lionel-k , that's what I do normally  first and at the second time I thought that you merged it with master after you merge the branch feature/add-chakra-ui I merged first with feature/add-chakra-ui and then with master.
Screenshot_20201122_113755

**Comment by muco-rolle** [comment]
Can you show me a screenshot??

**Review by lionel-k — APPROVED** [review]

**Comment by lionel-k** [comment]
Here it depends on which version of master you have.

I normally do `git fetch && git merge origin/master` in my local branch to be sure I'm merging
with the latest version of master

**Pull request merged**
